name: zig CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0-dev.172+a11dfaf61
      - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - run: zig build -Dtarget=x86_64-linux -Dwith_gpgme=false run
